name: tuition_attendance
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^5.4.7
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.15.5+2
  google_sign_in: ^4.1.4
  provider: ^4.0.4
  google_fonts: ^0.3.9
  toast: ^0.1.5
  firebase_crashlytics: ^0.1.3+3
  firebase_analytics: ^5.0.11
  flutter_spinkit: ^4.1.2
  firebase_storage: ^3.1.3
  cached_network_image: ^2.0.0
  image_picker: ^0.6.3+4
  flutter_form_builder: ^3.8.1
  progress_dialog: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
