name: tuition_attendance
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.15.5+2
  google_sign_in: ^4.1.4
  provider: ^4.0.4
  font_awesome_flutter: ^8.7.0
  google_fonts: ^0.3.9
  toast: ^0.1.5
  permission_handler: ^4.4.0+hotfix.1
  share: ^0.6.3+6
  rate_my_app: ^0.6.0+2
  connectivity: ^0.4.8+2
  firebase_crashlytics: ^0.1.3+3
  shared_preferences: ^0.5.6+3
  flutter_local_notifications: ^1.2.2
  firebase_analytics: ^5.0.11
  flutter_spinkit: ^4.1.2
  firebase_storage: ^3.1.3
  cached_network_image: ^2.0.0
  image_picker: ^0.6.3+4
  flutter_form_builder: ^3.8.1
  progress_dialog: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
